HIP_PATH?= /opt/rocm
HIPCC=$(HIP_PATH)/bin/hipcc
ROCOBJDUMP = $(HIP_PATH)/llvm/bin/llvm-objdump

GEM5_PATH = /home/intern/luot/gem5
CXXFLAGS += -I\$(GEM5_PATH)/include
CXXFLAGS += -I\$(GEM5_PATH)/util/m5/src
LDFLAGS  += -I$(GEM5_PATH)/util/m5/build/x86/out -lm5

EXECUTABLE = square.default
CPPSRC = square-1.cpp


OPTS = -O3 -Wno-unused-result
BIN_DIR?= ./bin.default
DEVICE_OBJ := $(BIN_DIR)/a.out-hip-amdgcn-amd-amdhsa-gfx942
ASM_FILE := $(BIN_DIR)/square.asm

square: $(BIN_DIR)/$(EXECUTABLE)

$(BIN_DIR)/$(EXECUTABLE): $(CPPSRC) $(BIN_DIR)
	$(HIPCC) $(OPTS) --offload-arch=gfx942 --save-temps -fgpu-rdc $(CXXFLAGS) $(CPPSRC) -o $(BIN_DIR)/$(EXECUTABLE)
	@mv *.o *.hipfb *.mcin *.s *.bc *.txt *.hipi *.mcin $(BIN_DIR)/
	@mv a.out-hip-amdgcn-amd-amdhsa-gfx942 $(BIN_DIR)/

asm: $(ASM_FILE)

$(ASM_FILE): $(DEVICE_OBJ)
	$(ROCOBJDUMP) -d $(DEVICE_OBJ) > $(ASM_FILE)
	@echo "[✓] Disassembly saved to $(ASM_FILE)"

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

clean:
	rm -f $(BIN_DIR)/$(EXECUTABLE)
	rm -f $(DEVICE_OBJ)
	rm -f $(BIN_DIR)*.mcin $(BIN_DIR)*.o $(BIN_DIR)*.hipfb $(BIN_DIR)*.mcin $(BIN_DIR)*.s $(BIN_DIR)*.bc $(BIN_DIR)*.txt $(BIN_DIR)*.hipi
	rmdir --ignore-fail-on-non-empty $(BIN_DIR)

.PHONY: square clean
